version: '{build}'
image: Visual Studio 2017
configuration: Release

before_build:
- cmd: dotnet restore

artifacts:
  - path: '**\*.nupkg'
  
deploy:
- provider: NuGet
  api_key:
    secure: /4N7ion7O3kWuiM5LEiU9oyfmPYGAbJxic7AFKSX/4Z1iiMwdxAUf3v7v6EvFgyZ
  on:
    appveyor_repo_tag: true
