//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FluentAssertions.Mvc {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FailureMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal FailureMessages() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FluentAssertions.AspNetCore.Mvc.FailureMessages", typeof(FailureMessages).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Expected {0} to be &apos;{1}&apos; but found &apos;{2}&apos;.
        /// </summary>
        public static string CommonFailMessage {
            get {
                return ResourceManager.GetString("CommonFailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to RouteData.DataTokens does not contain key {0}..
        /// </summary>
        public static string RouteData_DataTokens_ContainsKey {
            get {
                return ResourceManager.GetString("RouteData_DataTokens_ContainsKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Expected RouteData.DataTokens[{0}] to have value {1}, but found {2}..
        /// </summary>
        public static string RouteData_DataTokens_HaveValue {
            get {
                return ResourceManager.GetString("RouteData_DataTokens_HaveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to RouteData.Values does not contain key {0}..
        /// </summary>
        public static string RouteData_Values_ContainsKey {
            get {
                return ResourceManager.GetString("RouteData_Values_ContainsKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Expected RouteData.Values[{0}] to have value {1}, but found {2}..
        /// </summary>
        public static string RouteData_Values_HaveValue {
            get {
                return ResourceManager.GetString("RouteData_Values_HaveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Expected MasterName to be {0} but found {1}..
        /// </summary>
        public static string ViewResult_MasterName {
            get {
                return ResourceManager.GetString("ViewResult_MasterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Expected Model to be of type {0}, but no Model was supplied..
        /// </summary>
        public static string ViewResultBase_NullModel {
            get {
                return ResourceManager.GetString("ViewResultBase_NullModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ViewData does not contain key of {0}..
        /// </summary>
        public static string ViewResultBase_ViewData_ContainsKey {
            get {
                return ResourceManager.GetString("ViewResultBase_ViewData_ContainsKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Expected ViewData[{0}] to have value {1}, but found {2}..
        /// </summary>
        public static string ViewResultBase_ViewData_HaveValue {
            get {
                return ResourceManager.GetString("ViewResultBase_ViewData_HaveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Expected ViewName to be {0} but found {1}..
        /// </summary>
        public static string ViewResultBase_ViewName {
            get {
                return ResourceManager.GetString("ViewResultBase_ViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Expected default view, but view {0} was rendered..
        /// </summary>
        public static string ViewResultBase_WithDefaultViewName {
            get {
                return ResourceManager.GetString("ViewResultBase_WithDefaultViewName", resourceCulture);
            }
        }
    }
}
