//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FluentAssertions.AspNetCore.Mvc {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FailureMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FailureMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FluentAssertions.AspNetCore.Mvc.FailureMessages", typeof(FailureMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected AuthenticationSchemes to contain Scheme {0}..
        /// </summary>
        internal static string CommonAuthenticationSchemesContainScheme {
            get {
                return ResourceManager.GetString("CommonAuthenticationSchemesContainScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected {context} to be {0}{reason} but found {1}..
        /// </summary>
        internal static string CommonFailMessage {
            get {
                return ResourceManager.GetString("CommonFailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Items to contain [{0},{1}]..
        /// </summary>
        internal static string CommonItemsContain {
            get {
                return ResourceManager.GetString("CommonItemsContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected {0} List to contain exact items of actual items. .
        /// </summary>
        internal static string CommonListsNotIdentical {
            get {
                return ResourceManager.GetString("CommonListsNotIdentical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected {context} to be of type {0}, but no value was supplied..
        /// </summary>
        internal static string CommonNullWasSuppliedFailMessage {
            get {
                return ResourceManager.GetString("CommonNullWasSuppliedFailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected {context} to be of type {0} but was {1}{reason}..
        /// </summary>
        internal static string CommonTypeFailMessage {
            get {
                return ResourceManager.GetString("CommonTypeFailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected {context} to be ActionResult&lt;TValue&gt; with type {0}{reason} but was {1}..
        /// </summary>
        internal static string ConvertibelModelFailMessage {
            get {
                return ResourceManager.GetString("ConvertibelModelFailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected {context} to be convertible to {0} but it was {1}..
        /// </summary>
        internal static string ConvertibleActionFailMessage {
            get {
                return ResourceManager.GetString("ConvertibleActionFailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected FileContentResult.FileContents to have {0} byte(s){reason} but found {1}..
        /// </summary>
        internal static string FileContentResult_WithFileContents_LengthFail {
            get {
                return ResourceManager.GetString("FileContentResult_WithFileContents_LengthFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected FileContentResult.FileContents[{0}] to be {1:x2}{reason} but found {2:x2}..
        /// </summary>
        internal static string FileContentResult_WithFileContents_MatchFail {
            get {
                return ResourceManager.GetString("FileContentResult_WithFileContents_MatchFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected default view{reason}, but view {0} was rendered..
        /// </summary>
        internal static string ViewResultBase_WithDefaultViewName {
            get {
                return ResourceManager.GetString("ViewResultBase_WithDefaultViewName", resourceCulture);
            }
        }
    }
}
